### PR TITLE
Expose proper PID on windows and clean up process handle

### LINKED ISSUE #45: Wrong pid on windows: Error: kill ESRCH
Every new started process gets wrong pid which is different from ones shown in `task manager`.
Could be reproduced with the [demo of xterm.js](https://github.com/sourcelair/xterm.js/tree/bebe43e5e108b081a8ead57b881e7ea1504164d7/demo).
Related to [xterm.js issue](https://github.com/sourcelair/xterm.js/pull/584).

```sh
> xterm@2.3.2 start C:\Users\coderaiser\Documents\GitHub\xterm.js
> node demo/app

App listening to http://127.0.0.1:3000
Created terminal with PID: 928
Connected to terminal 928
internal/process.js:173
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:173:13)
    at WebSocket.<anonymous> (C:\Users\coderaiser\Documents\GitHub\xterm.js\demo\app.js:72:13)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\coderaiser\Documents\GitHub\xterm.js\node_modules\ws\lib\WebSocket.js:950:8)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.3.2 start: `node demo/app`
npm ERR! Exit status 1
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #45 

@rprichard a quick review of the handle clean up would be greatly appreciated 😃

### CODE REVIEW

File: src/win/pty.cc [hunk 1]
```diff
@@ -311,18 +313,21 @@ static NAN_METHOD(PtyResize) {
...
-    || !info[0]->IsNumber()) // pid
+  if (info.Length() != 2
+    || !info[0]->IsNumber() // pid
+    || !info[1]->IsNumber()) // innerPidHandle
   {
     return Nan::ThrowError("Usage: pty.kill(pid)");
   }
 
   int handle = info[0]->Int32Value();
+  HANDLE innerPidHandle = (HANDLE)info[0]->Int32Value();
```
Comment (rprichard) [inline src/win/pty.cc]: Is this supposed to be `info[1]->Int32Value`?

File: src/win/pty.cc [hunk 2]
```diff
@@ -311,18 +313,21 @@ static NAN_METHOD(PtyResize) {
 static NAN_METHOD(PtyKill) {
   Nan::HandleScope scope;
 
-  if (info.Length() != 1
-    || !info[0]->IsNumber()) // pid
+  if (info.Length() != 2
+    || !info[0]->IsNumber() // pid
+    || !info[1]->IsNumber()) // innerPidHandle
   {
     return Nan::ThrowError("Usage: pty.kill(pid)");
```
Comment (rprichard) [inline src/win/pty.cc]: nit: I suppose this usage string is now incorrect -- i.e. it should be something like `pty.kill(pid, innerPidHandle)`

**Comment by Tyriar** [comment]
@rprichard great feedback thanks, I made the changes.
